device: hdd1
description: "hard-coded disassembly sequence for HDD1"
sequence:
- affordance_name: InitializeRobotAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

# disassemble the lid by unscrewing and shaking
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '6'


- affordance_name: CuttingAction
  asc:
  - key: CuttingPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.304
        y: -0.025
        z: -0.012

# Flip to the opposite side
- affordance_name: FlippingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''


# disassemble the lid by unscrewing and shaking
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '0'


- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.238
        y: 0.005
        z: 0.024

- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.238
        y: 0.005
        z: -0.020

- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.278
        y: 0.005
        z: -0.018

- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.283
        y: 0.005
        z: 0.024


- affordance_name: ShakingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''


- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '-1'

