device: hdd1
description: "hard-coded disassembly sequence for HDD1"
sequence:
- affordance_name: InitializeRobotAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

# disassemble the lid by unscrewing and shaking
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '0'


- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.292
        y: 0.018
        z: 0.017

- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.292
        y: 0.018
        z: 0.017

- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.292
        y: 0.018
        z: 0.017

- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.292
        y: 0.018
        z: 0.017


- affordance_name: ShakingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

# disassemble the lid by unscrewing and shaking
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '6'


- affordance_name: CuttingAction
  asc:
  - key: CutPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.292
        y: 0.018
        z: 0.017

- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '-1'

