device: hdd1
description: "hard-coded disassembly sequence for HDD1"
sequence:
#- affordance_name: SuckingAction
#  asc:
#  - key: SuckingPose
#    value_type: 2
#    value_pose:
#        qw: 0.70572561025619507
#        qx: 0.70672500133514404
#        qy: 0.04416978731751442
#        qz: -0.02325459755957126
#        x: 0.240
#        y: 0.045
#        z: 0.006
#  - key: SuckingPower
#    value_type: 1
#    value_double: 5.0

- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '4'

#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.296
#        y: 0.008
#        z: 0.014

#  - key: ScrewDir
#    value_type: 1
#    value_double: 0

#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '-1'
