device: hdd2
description: "hard-coded disassembly sequence for HDD2"
sequence:

- affordance_name: InitializeRobotAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

# disassemble the lid by unscrewing and shaking
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '4'


- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.259
        y: 0.018
        z: 0.061

- affordance_name: ShakingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''


# disassemble the magnet
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '5'

- affordance_name: LeveringAction  # check this if
  asc:
  - key: LeverPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.287
        y: 0.114
        z: -0.089

# change tools for unscrew
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '4'

# unscrew the platter
- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.238
        y: 0.016
        z: 0.002

# unscrew read-write head
- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.270
        y: 0.005
        z: 0.050


# change tools for unscrew of read write head
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '1'

# unscrew the platter
- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.288
        y: 0.016
        z: 0.006

- affordance_name: ShakingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

# change tools for unscrew
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '4'

# unscrew the motor and drop them all
- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.311
        y: 0.004
        z: 0.013


- affordance_name: ShakingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

# Flip to the opposite side
- affordance_name: FlippingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

# unscrew pcb
- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.250
        y: 0.008
        z: -0.033

- affordance_name: ShakingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

# Drop the tool and go for sucking action
- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '-1'

# open jaw action and reset robot
- affordance_name: OpenJawAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

#- affordance_name: CloseAndLevelJawAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''



