device: hdd4
description: "hard-coded disassembly sequence for HDD4"
sequence:
## disassemble the lid by unscrewing and shaking
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '4'


#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.287
#        y: 0.018
#        z: 0.029

#- affordance_name: ShakingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## unscrew magnet
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.270
#        y: 0.014
#        z: 0.057

#- affordance_name: ShakingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## disassemble the magnet
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '5'

#- affordance_name: LeveringAction  # check this if
#  asc:
#  - key: LeverPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.292
#        y: 0.099
#        z: 0.114

#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '2'

## ========== screw too small, very difficult ===========
## unscrew the platter
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.240
#        y: 0.016
#        z: 0.001

### ========== screw too small, don't do it ===========
### unscrew read-write head
##- affordance_name: UnscrewingAction
##  asc:
##  - key: ScrewPose
##    value_type: 2
##    value_pose:
##        qw: 1
##        qx: 0
##        qy: 0
##        qz: 0
##        x: 0.302
##        y: 0.015
##        z: -0.027

#- affordance_name: ShakingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## Flip to the opposite side
#- affordance_name: FlippingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## ========== Tool stuck in the hole ===========
## Cutting action
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '6'

## Cutting
#- affordance_name: CuttingAction
#  asc:
#  - key: CutPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.256
#        y: 0.016
#        z: 0.017

## disassemble the PCB
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '4'

## unscrew pcb
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.304
#        y: 0.016
#        z: 0.021

#- affordance_name: ShakingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## unscrew the read write header
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.285
#        y: 0.010
#        z: -0.01

## Flip to the opposite side
#- affordance_name: FlippingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## unscrew the motor
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.239
#        y: 0.010
#        z: -0.012

#- affordance_name: FlippingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## push the motor
#- affordance_name: PushingAction
#  asc:
#  - key: PushPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.231
#        y: 0.014
#        z: 0.008
#  - key: PushDir
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.0
#        y: -0.02
#        z: 0.0

## return tool and finish
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '-1'


