device: hdd5
description: "hard-coded disassembly sequence for HDD1"
sequence:

- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '4'


- affordance_name: UnscrewingAction
  asc:
  - key: ScrewPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.296
        y: 0.008
        z: 0.014

- affordance_name: FlippingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''

- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '4'
