device: hdd5
description: "hard-coded disassembly sequence for HDD5"
sequence:
## disassemble the lid by unscrewing and shaking
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '4'


#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.287
#        y: 0.018
#        z: 0.023

#- affordance_name: ShakingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## unscrew magnet
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.272
#        y: 0.014
#        z: 0.057

## disassemble the magnet
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '5'

#- affordance_name: LeveringAction  # check this if
#  asc:
#  - key: LeverPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.292
#        y: 0.099
#        z: 0.114

- affordance_name: SwitchToolAction
  asc:
  - key: ToolIndex
    value_type: 0
    value_str: '2'

## unscrew the platter
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.240
#        y: 0.016
#        z: 0.003

## unscrew read-write head
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.300
#        y: 0.000
#        z: -0.017

#- affordance_name: ShakingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## Flip to the opposite side
#- affordance_name: FlippingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

## Cutting action
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '6'

## Cutting
#- affordance_name: CuttingAction
#  asc:
#  - key: CutPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.259
#        y: 0.016
#        z: 0.022

## disassemble the PCB
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '4'

## unscrew pcb
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.259
#        y: 0.016
#        z: 0.022

#- affordance_name: ShakingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''


## change tools for unscrew (torx8)
#- affordance_name: SwitchToolAction
#  asc:
#  - key: ToolIndex
#    value_type: 0
#    value_str: '4'

## unscrew the read write header
#- affordance_name: UnscrewingAction
#  asc:
#  - key: ScrewPose
#    value_type: 2
#    value_pose:
#        qw: 1
#        qx: 0
#        qy: 0
#        qz: 0
#        x: 0.277
#        y: 0.004
#        z: 0.046

## Flip to the opposite side
#- affordance_name: FlippingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''


