device: test_action
description: "for testing different actions and functionalities"
sequence:
- affordance_name: FlippingAction
  asc:
  - key: ''
    value_type: 0
    value_str: ''
  - key: 'OnlySimulateAction'
    value_type: 0
    value_str: 'Yes'

- affordance_name: LeveringAction
  asc:
  - key: LeverPose
    value_type: 2
    value_pose:
        qw: 1
        qx: 0
        qy: 0
        qz: 0
        x: 0.292
        y: 0.099
        z: 0.114
  - key: 'OnlySimulateAction'
    value_type: 0
    value_str: 'Yes'

#- affordance_name: RotatingBaseAction
#  asc:
#  - key: 'FlipAngle'
#    value_type: 1
#    value_double: 70

#- affordance_name: FlippingAction
#  asc:
#  - key: ''
#    value_type: 0
#    value_str: ''

#- affordance_name: RotatingBaseAction
#  asc:
#  - key: 'FlipAngle'
#    value_type: 1
#    value_double: 70
